name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        pip-version: ["1.4.2"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache Pip packages
      id: pip-cache
      uses: actions/cache@v3
      with:
        path: pip-dep-path.outputs.stdout
        key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      if: steps.pip-cache.outputs.cache-hit != 'true'

    - name: Test with unittest
      run: |
        python -m unittest
      env:
        CARBONATE_USER_ID: ${{ secrets.CARBONATE_USER_ID }}
        CARBONATE_API_KEY: ${{ secrets.CARBONATE_API_KEY }}
